In [1]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
import xarray as xr
import matplotlib.pyplot as plt

In [36]:
param_root='/glade/u/home/rfisher/rosiefork_fates_global_cal/rosie_ppe/gaussian_emulator/parameter_outputs/'

param_file='SP_LHC_calibration_TESTED_june27_crops.nc'
newfile='SP_LHC_calibration_TESTED_june27_crops.nc'

In [37]:
pfile=param_root+param_file
print(pfile)

/glade/u/home/rfisher/rosiefork_fates_global_cal/rosie_ppe/gaussian_emulator/parameter_outputs/SP_LHC_calibration_TESTED_june27_crops.nc


In [38]:
pdata=xr.open_dataset(pfile)

In [39]:
pdata.fates_hlm_pft_map.values

array([[ 0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  

In [33]:
pdata.fates_leaf_vcmax25top.values[0,0]

54.16785357071415

In [41]:
pdata.fates_rad_model.values

array(nan)

In [40]:
pdata.fates_hlm_pftno

<xarray.DataArray 'fates_hlm_pftno' (fates_hlm_pftno: 16)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
Dimensions without coordinates: fates_hlm_pftno

In [20]:

print(pdata.fates_hlm_pftno)
new_fates_hlm_pftno = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
print(new_fates_hlm_pftno)
pdata = pdata.reindex(fates_hlm_pftno=new_fates_hlm_pftno)

pdata.to_netcdf(new_file)

<xarray.DataArray 'fates_hlm_pftno' (fates_hlm_pftno: 14)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
Dimensions without coordinates: fates_hlm_pftno
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


ValueError: cannot reindex or align along dimension 'fates_hlm_pftno' because of conflicting dimension sizes: {16, 14} (note: an index is found along that dimension with size=16)

In [11]:
calibfile=xr.open_dataset('/glade/u/home/rfisher/rosiefork_fates_global_cal/rosie_ppe/gaussian_emulator/parameter_outputs/SP_LHC_calibration_1_3.nc')

In [13]:
calibfile.fates_rad_model.values

array(2.)