In [1]:
import os
import numpy as np
import netCDF4 as nc4
import shutil
import warnings
warnings.filterwarnings('ignore')
import xarray as xr
from matplotlib import pyplot as plt

In [10]:
# make manual adjustments to SP calibration scheme. 

pfile1='parameter_outputs/manual_nocomp_calibration_04july.nc'

newfile='parameter_outputs/manual_nocomp_calibration__16july.nc'

pf=xr.open_dataset(pfile1)

pft=0 # BET
pf['fates_leaf_slatop'][pft]=0.014 # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45
pf['fates_maintresp_leaf_atkin2017_baserate'][pft]=1.734
print('pft',pft,pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=55.12
print('pft',pft,'vcmax',pf['fates_leaf_vcmax25top'][0,pft].values)

pft=1 # NET
print(pf['fates_leaf_slatop'][pft].values)
pf['fates_leaf_slatop'][pft]=0.007  # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45

pft=2 # NDT - make a little lower
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25

pft=4 # DDT 
pf['fates_leaf_vcmax25top'][0,pft]=40

pft=8 #dec shrub (GPP is too high needs to be reduced). 
print('vcm dec sh',pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=35
print('vcm dec sh',pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_allom_d2bl1'][pft]=0.05

pft=9 # ArcC3G
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=40
pf['fates_allom_d2bl1'][pft]=0.05
print('vcm arcc3',pf['fates_leaf_vcmax25top'][0,pft].values)

pft=10 # C3G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05

pft=11 # C4G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05
    
pf.to_netcdf(newfile)
pf.close()

pft 0 71.3476695339068
pft 0 vcmax 55.12
0.007
vcm dec sh 35.0
vcm dec sh 35.0
40.0
vcm arcc3 40.0


In [8]:
# make manual adjustments to SP calibration scheme. 
ensN=2
pfile1 = 'parameter_outputs/SP_LHC_calibration_2_3.nc'

newfile='parameter_outputs/manual_nocomp_calibration_04july.nc'

pf=xr.open_dataset(pfile1)

pft=0 # BET
pf['fates_leaf_slatop'][pft]=0.014 # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45
print(pft,pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=55.12
print('pft',pft,'vcmax',pf['fates_leaf_vcmax25top'][0,pft].values)

pft=1 # NET
print('sla p1',pf['fates_leaf_slatop'][pft].values)
pf['fates_leaf_slatop'][pft]=0.007  # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45

pft=2 # NDT - make a little lower
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25

pft=4 # DDT 
pf['fates_leaf_vcmax25top'][0,pft]=40

pft=8 #dec shrub (GPP is too high needs to be reduced). 
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=35
print(pf['fates_leaf_vcmax25top'][0,pft].values)

pft=9 # ArcC3G
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=40
print(pf['fates_leaf_vcmax25top'][0,pft].values)

pft=10 # C3G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05

pft=11 # C4G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05
    
#pf.to_netcdf(newfile)
pf.close()

0 66.09695939187839
pft 0 vcmax 55.12
sla p1 0.005
54.0
35.0
78.0
40.0


In [4]:
# make manual adjustments to SP calibration scheme. 
ensN=2
pfile1 = 'parameter_outputs/SP_LHC_calibration_2_3.nc'

newfile='parameter_outputs/manual_nocomp_calibration_29junb.nc'

pf=xr.open_dataset(pfile1)

pft=0 # BET
pf['fates_leaf_slatop'][pft]=0.014 # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45

pft=1 # NET
print(pf['fates_leaf_slatop'][pft].values)
pf['fates_leaf_slatop'][pft]=0.007  # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45

pft=2 # NDT - make a little lower
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25

pft=4 # DDT 
pf['fates_leaf_vcmax25top'][0,pft]=40

pft=8 #dec shrub (GPP is too high needs to be reduced). 
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=40
print(pf['fates_leaf_vcmax25top'][0,pft].values)

pft=9 # ArcC3G
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=50
print(pf['fates_leaf_vcmax25top'][0,pft].values)

pft=10 # C3G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05

pft=11 # C4G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05
    
#pf.to_netcdf(newfile)
pf.close()

0.005
54.0
40.0
78.0
50.0


In [4]:
#28 jun
if(pfile==5):
    pft=0 # BET
    pf['fates_leaf_slatop'][pft]=0.025  # lai needs to be higher. 
    pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.00  
    pf['fates_allom_d2ca_coefficient_min'][pft]=0.2  
    
    pft=1 # NET
    pf['fates_leaf_slatop'][pft]=0.018  # LAI needs to be higher
    pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
    pf['fates_allom_d2ca_coefficient_min'][pft]=0.45
    
    pft=2 # NDT - make a little lower
    pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
    
    pft=10 # DDT 
    pf['fates_leaf_vcmax25top'][0,pft]=40
    
    pft=9 # ArcC3G
    print(pf['fates_leaf_vcmax25top'][0,pft].values)
    
    pft=10 # C3G
    pf['fates_leaf_vcmax25top'][0,pft]=50
    print(pf['fates_leaf_vcmax25top'][0,pft].values)
    pft=10 # coolC3G
    pf['fates_turnover_leaf'][0,pft]=0.75
    pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
    
    pft=11 # coolC3G
    pf['fates_turnover_leaf'][0,pft]=0.75
    pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
    
 

NameError: name 'pfile' is not defined

In [ ]:
#29jun

pft=1 # NET
#pf['fates_leaf_slatop'][pft]=0.018  # LAI needs to be higher
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=1.5
#pf['fates_allom_d2ca_coefficient_min'][pft]=0.45

pft=2 # NDT - make a little lower
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25

pft=4 # DDT 
pf['fates_leaf_vcmax25top'][0,pft]=40

pft=9 # ArcC3G
print(pf['fates_leaf_vcmax25top'][0,pft].values)
pf['fates_leaf_vcmax25top'][0,pft]=50
print(pf['fates_leaf_vcmax25top'][0,pft].values)

pft=10 # coolC3G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05

pft=11 # coolC4G
pf['fates_turnover_leaf'][0,pft]=0.75
pf['fates_maintresp_leaf_vert_scaler_coeff2'][pft]=2.25
pf['fates_allom_d2bl1'][pft]=0.05
    


In [2]:
newfile='parameter_outputs/manual_nocomp_calibration_29jun.nc'
pf=xr.open_dataset(newfile)
print(pf['fates_leaf_vcmax25top'][0,:].values)
print(pf['fates_maintresp_leaf_vert_scaler_coeff2'][:].values)
print(pf['fates_allom_d2bl1'][:].values)
pf.close()

[71.34766953 62.         39.         61.         40.         58.
 62.         54.         54.         50.         80.         20.        ]
[2.43 1.5  2.25 2.43 2.43 2.43 2.43 2.43 2.43 2.43 2.25 2.25]
[0.04 0.07 0.07 0.01 0.04 0.07 0.07 0.07 0.07 0.07 0.05 0.05]


In [3]:
newfile='parameter_outputs/manual_nocomp_calibration_29junb.nc'
pf=xr.open_dataset(newfile)
print(pf['fates_leaf_vcmax25top'][0,:].values)
print(pf['fates_maintresp_leaf_vert_scaler_coeff2'][:].values)
print(pf['fates_allom_d2bl1'][:].values)
pf.close()

[71.34766953 62.         39.         61.         40.         58.
 62.         54.         40.         50.         80.         20.        ]
[1.5  1.5  2.25 2.43 2.43 2.43 2.43 2.43 2.43 2.43 2.25 2.25]
[0.04 0.07 0.07 0.01 0.04 0.07 0.07 0.07 0.07 0.07 0.05 0.05]


In [4]:
newfile='parameter_outputs/manual_nocomp_calibration_04july.nc'
pf=xr.open_dataset(newfile)
print(pf['fates_leaf_vcmax25top'][0,:].values)
print(pf['fates_maintresp_leaf_vert_scaler_coeff2'][:].values)
print(pf['fates_allom_d2bl1'][:].values)
pf.close()

[71.34766953 62.         39.         61.         40.         58.
 62.         54.         35.         40.         80.         20.        ]
[1.5  1.5  2.25 2.43 2.43 2.43 2.43 2.43 2.43 2.43 2.25 2.25]
[0.04 0.07 0.07 0.01 0.04 0.07 0.07 0.07 0.07 0.07 0.05 0.05]
