Notebook to calculate the mean parameter fields from Adrianna's SP calibration

### Read in parameter files

In [15]:
import os
import netCDF4 as nc4
import sys
import shutil
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import xarray as xr
from matplotlib import pyplot as plt
#import datetime
import netCDF4 as nc4

In [63]:
root = '/glade/u/home/rfisher/lh_params_500_new'
os.chdir(root)
loopn=0

vcm=np.zeros((14, 500))
print(vcm)
with os.scandir(root) as it:
    for entry in it:
        if not entry.name.startswith('.') and entry.is_file():
            #print(entry.name)
            loopn=loopn+1
            pfilename = entry.name
            ncf = nc4.Dataset(pfilename)
            v=ncf.variables['fates_leaf_vcmax25top']
            print(v[0,:])
                  
            vcm[:,loopn]=v[0,:]
            #fin=nc4.Dataset(pfilename, 'r+')
            #data = fin.read()   #read file contents to string   

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[16.7556  21.82338 25.87663 61.      58.      58.      62.      54.
 54.      33.10484 33.28112 48.23365 78.      78.     ]
[15.1507  44.36979 38.54724 61.      58.      58.      62.      54.
 54.      13.54263 20.10898 62.27393 78.      78.     ]
[20.33019 42.34662 46.35858 61.      58.      58.      62.      54.
 54.      68.63545 27.99734 70.47267 78.      78.     ]
[16.08749 53.00777 12.55608 61.      58.      58.      62.      54.
 54.      71.02591 17.33545 34.75188 78.      78.     ]
[24.6581  19.35549 99.04641 61.      58.      58.      62.      54.
 54.      74.99164 17.81443 33.37061 78.      78.     ]
[62.63492 19.35549 25.11239 61.      58.      58.      62.      54.
 54.      77.988   17.90148 54.12715 78.      78.     ]
[23.85601 25.93521 48.75966 61.      58.      58.      62.      54.
 54.      46.56867 18.69589 35.0

IndexError: index 500 is out of bounds for axis 1 with size 500

In [46]:
v=ncf.variables['fates_leaf_vcmax25top']
print(v[0,:])

[22.78026 34.49523 88.64637 61.      58.      58.      62.      54.
 54.      39.27026 29.84007 32.4081  78.      78.     ]
